### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by ghost** [nicfel/The-Structured-Coalescent#1]
@nicfel Could you please send me all the data that can not allow to put them of gitlab due to the big size of them, I want to redo your analysis, thanks.

**Comment by nicfel** [comment]
The run files for the AIV example can be found here: https://github.com/nicfel/The-Structured-Coalescent/tree/master/AIV/structcoal/individual. Let me know if you need the Simulation files as well (they can be quite large)

Cheers,
Nicola
